---
 - name: copy /etc/zabbix/zabbix_tpu.py files
   copy: src=zabbix_tpu.py   dest=/etc/zabbix/zabbix_tpu.py  mode=0755  owner=root group=root

 - name: copy /etc/zabbix/tpu_log_analyzer.awk files
   copy: src=tpu_log_analyzer.awk dest=/etc/zabbix/tpu_log_analyzer.awk mode=0755  owner=root group=root

- name: check tpu crontab
   shell: grep '/usr/bin/python /etc/zabbix/zabbix_tpu.py'  /var/spool/cron/root |wc -l
   register: tpu_crontab_file

 - name: set tpu crontab
   cron: name="zabbix tpu crontab" minute="*/5" job="/usr/bin/python /etc/zabbix/zabbix_tpu.py" user=root
   when: tpu_crontab_file == 0

 - include: log.yml
 - include: statists.yml
