---
 - name: corpy /etc/zabbix/zabbix_lb.py 
   copy: src=zabbix_lb.py dest=/etc/zabbix/zabbix_lb.py mode=0775
 
 - name: set lb crontab
   cron: name="zabbix lb crontab" minute="*/1" job="/usr/bin/python /etc/zabbix/zabbix_lb.py" user=root 

 - include: log.yml
 - include: statists.yml
