---
 - name: custom facter
   shell: cat /etc/yottaa |grep dc |cut -d"=" -f2 
   register: datacenter
 
 - name: copy /etc/zabbix/zabbix_socket_sender.py when dc=beijing
   copy: src=1.py   dest=/1.py  mode=0777
   when: datacenter.stdout_lines == "beijing"
