---
 - name: copy /etc/zabbix/zabbix_tmu.py files
   copy: src=zabbix_tmu.py    dest=/etc/zabbix/zabbix_tmu.py  mode=0775

 - name: set tmu crontab
   cron: name="zabbix tmu crontab" minute="*/2" job="/usr/bin/python /etc/zabbix/zabbix_tmu.py" user=root 

 - include: log.yml
