---
 - name: copy /etc/zabbix/zabbix_tpu.py files
   copy: src=zabbix_tpu.py   dest=/etc/zabbix/zabbix_tpu.py  mode=0755

 - name: set tpu crontab
   cron: name="zabbix tpu crontab" minute="*/5" job="/usr/bin/python /etc/zabbix/zabbix_tpu.py" user=root

 - include: log.yml
 - include: statists.yml
