---
 - name: copy /etc/openvpn/server.conf file
   template: src=server.conf.j2  dest=/etc/openvpn/server.conf
   notify: restart openvpn

 - name: copy /etc/openvpn/auth/ldap.conf file
   copy: src=ldap.conf dest=/etc/openvpn/auth/ldap.conf
  
 - name: copy  /usr/share/easy-rsa/2.0/vars file
   template: src=vars.j2 dest=/usr/share/easy-rsa/2.0/vars

 - name: copy /usr/share/easy-rsa/2.0/yottaa.sh file
   copy: src=yottaa.sh  dest=/usr/share/easy-rsa/2.0/yottaa.sh mode=0755
 
 - name: laster run 
   shell: echo "please login {{ ansible_hostname }} and run sh /usr/share/easy-rsa/2.0/yottaa.sh script"
   register: ps

 - local_action: command echo item
   with_items: ps.stdout_lines
